### ISSUE TITLE
ProcessEventData Error

### ISSUE THREAD

**Issue by 4PsyMi** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#13]
Hello, i tried to install this AC, everything seemed to work but as soon as someone connects to the server i get this error:
[script:IcarusAdvance] > handler (@IcarusAdvancedAnticheat/core/server/event_handler.lua:49)
[script:IcarusAdvance] SCRIPT ERROR: @IcarusAdvancedAnticheat/core/server/event_handler.lua:49: attempt to call a nil value (field 'ProcessEventData')
I hope you can fix this or atleast know what to do ^^
Have a great day!

**Comment by EinS4ckZwiebeln** [comment]
Hello, thanks for informing me about this issue.
For now, until I have time to actually fix this, it can be resolved by **enabling the CreateEntity** module.

Your server config should look like this for now:
` 
EntityCreate = {
    enabled = true,
    banNetworkOwner = true
}
`

**Comment by 4PsyMi** [comment]
first of all thank you for your response. But i dont get it... I tried to put this line in my server.cfg but i still get the same error message. Could you tell me where exactly i should put this line or where i have to change something to succesfully get the AC to work properly?

**Comment by 4PsyMi** [comment]
if you dont mind, you can contact me on Discord. I guess your german too? Your name says it all xD
4PsyMi#7722
Would be great to get some help because your AC is the best free one i found so far (and i found A LOT of them xD)
