### ISSUE TITLE
When Enabling kick for using a VPN

### ISSUE THREAD

**Issue by R3tr0Ananas** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#16]
![grafik](https://user-images.githubusercontent.com/83706294/231672016-3a813ddb-407d-4fa8-9c8b-bc8f8390d83e.png)

The Player is stuck on deferring...

**Comment by EinS4ckZwiebeln** [comment]
In theory this should be resolved in the latest release. 
However if you still run into problems feel free to let me know via a new issue :)
