### ISSUE TITLE
Adding Anti-invisibility

### ISSUE THREAD

**Issue by ghost** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#17]
Add a check to check if the Player is Invisible if so then just make them visible.

**Comment by R3tr0Ananas** [comment]
i could code that but only in lua.

I am not so good in JS.

**Comment by EinS4ckZwiebeln** [comment]
Will look into this, thanks for the suggestion!

**Comment by EinS4ckZwiebeln** [comment]
Checking for invis is too prone for false positives. Closing this until someone comes up with a reasonable detection method.
