### ISSUE TITLE
How to unban someone

### ISSUE THREAD

**Issue by Bdotv2** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#19]
How do you unban someone it false ban two of my members and there is no way to unban them

**Comment by EinS4ckZwiebeln** [comment]
Please take a look at the README.md:

### Banning
Many anticheats come with custom ban-systems or databases. Icarus avoids such systems to improve compatibility and to steer clear of bloated code. To use Icarus properly **it is necessary to add your own ban logic** to the script. This can be done in the server configuration file.

```lua
function ServerConfig.BanPlayer(source, reason)
  -- Your own ban logic goes here.
  -- EXAMPLE: TriggerEvent("EasyAdmin:banPlayer", source, reason, 1044463300)
end
```
