### ISSUE TITLE
Adding my ban logic

### ISSUE THREAD

**Issue by Asogaming** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#20]
Hi!
I'm trying to add my ban logic to the config_sv.lua I have both txadmin and qb-adminmenu. I can't get it to work with either.

This is what i've got for a qb-adminmenu ban:

function ServerConfig.BanPlayer(source, reason)
    TriggerEvent("qb-admin:server:ban", player, time, reason, 2147483647)
end

**Comment by EinS4ckZwiebeln** [comment]
I have not tested this but you could try this:
```lua
local QBCore = exports["qb-core"]:GetCoreObject()

function ServerConfig.BanPlayer(source, reason)
	local player = QBCore.Functions.GetPlayer(source)
	TriggerEvent("qb-admin:server:ban", player, 2147483647, reason)
end
```
You might also look into the fundamentals of programming and [lua](https://www.lua.org/manual/5.4/) if you struggle with this :)
