### ISSUE TITLE
exports are giving error codes

### ISSUE THREAD

**Issue by damainman11** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#37]
when adding the export command to a script it just gives an error code instead
![Screenshot 2023-12-25 070830](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/154886956/da84e474-2462-404a-821e-8009815e462a)

**Comment by EinS4ckZwiebeln** [comment]
You need to make sure that the **export string matches the resource name**, since I forgot to update the example with the new resource name from the v2.x.x builds.

Your export should look like this now:
`exports["Icarus"]:AddExcuseForPlayer(source, 1000)`

However, if the issue still persists, please ensure that you are using the exports on the server side.

**Comment by damainman11** [comment]
> You need to make sure that the **export string matches the resource name**, since I forgot to update the example with the new resource name from the v2.x.x builds.
> 
> Your export should look like this now: `exports["Icarus"]:AddExcuseForPlayer(source, 1000)`
> 
> However, if the issue still persists, please ensure that you are using the exports on the server side.

Ahh.. Completely missed that thank you. Any plans on making an export for client side?

**Comment by EinS4ckZwiebeln** [comment]
> > You need to make sure that the **export string matches the resource name**, since I forgot to update the example with the new resource name from the v2.x.x builds.
> > Your export should look like this now: `exports["Icarus"]:AddExcuseForPlayer(source, 1000)`
> > However, if the issue still persists, please ensure that you are using the exports on the server side.
> 
> Ahh.. Completely missed that thank you. Any plans on making an export for client side?

No problem, you're welcome. There are no plans to add client-side exports related to excuses, since that would enable malicious actors to abuse the system. Handling bypasses on the server is crucial in terms of security.

**Comment by damainman11** [comment]
> > > You need to make sure that the **export string matches the resource name**, since I forgot to update the example with the new resource name from the v2.x.x builds.
> > > Your export should look like this now: `exports["Icarus"]:AddExcuseForPlayer(source, 1000)`
> > > However, if the issue still persists, please ensure that you are using the exports on the server side.
> > 
> > 
> > Ahh.. Completely missed that thank you. Any plans on making an export for client side?
> 
> No problem, you're welcome. There are no plans to add client-side exports related to excuses, since that would enable malicious actors to abuse the system. Handling bypasses on the server is crucial in terms of security.

Hmm.. Guess I'll have to figure something out since most scripts use client side teleportation and invisible for multicharacter selection

**Comment by EinS4ckZwiebeln** [comment]
> Hmm.. Guess I'll have to figure something out since most scripts use client side teleportation and invisible for multicharacter selection

I would suggest using a server callback if you are working with QBCore or ESX.
