### ISSUE TITLE
Super jump check suggestion

### ISSUE THREAD

**Issue by iSickos** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#5]
Hey, in addition to client side super jump check you could add server side check with IsPlayerUsingSuperJump() native
[https://docs.fivem.net/natives/?_0xC7D2C20C](url)

**Comment by EinS4ckZwiebeln** [comment]
Hi, how would you implement this? Just looping this native doesn’t seem like a good idea to me since it would have to be checked fairly often. This will cause severe performance issues at higher player counts.

**Comment by iSickos** [comment]
I was thinking that you could trigger server side check if player jumps. Did some optimization tweaks also added commented note where you could add server side check

**Comment by EinS4ckZwiebeln** [comment]
See #6 why this ain't a good idea to do.

**Comment by iSickos** [comment]
<a href="https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/pull/6#issuecomment-1435986527">#6</a> was more of an optimization. Right now you are writing startPos, endPos and calculating horizontalDist even if player is not jumping, you should fix that

**Comment by EinS4ckZwiebeln** [comment]
Will tackle this in a dedicated commit, or you could create a new commit without unnecessary comments and changes in syntax.
