### ISSUE TITLE
Toggling modules

### ISSUE THREAD

**Issue by YelehaUwU** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#62]
**Describe the bug**
Setting a module to false sometimes doesn't deactivate it (seen on Noclip and Super Jump so far).

**To Reproduce**
1. Set a module from true to false.
2. Get banned even if its set to false.

**Expected behavior**
Don't get banned in case of it being set to false.

**Screenshots**

**Technical Details:**
 - OS: Linux (Ubuntu 22.04) Running inside of a docker container
 - Artifacts: Latest
 - Icarus Version: Latest

**Additional context**
-

**Comment by EinS4ckZwiebeln** [comment]
Thanks for the report. I think this might be due to an oversight with the /unload command on my end. I will look into this asap!

**Comment by YelehaUwU** [comment]
I must add that I toggled the modules in the config, not using the command.

**Comment by EinS4ckZwiebeln** [comment]
Version 2.0.6 should fix the commands as well as the config not working properly. If the issue still persists pls report back. :)

**Comment by YelehaUwU** [comment]
![obrázok](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/162886331/079a5741-3421-44ca-b2fb-7e9592d05b6a)
![obrázok](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/162886331/dceb39b9-c8ee-4bab-99e6-8899f0ae5255)
It didn't help.

**Comment by EinS4ckZwiebeln** [comment]
Would you mind attaching your `config.lua` and recent logs from the `/logs/` directory?

**Comment by YelehaUwU** [comment]
[Debug.zip](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/14965365/Debug.zip)

As you can see in the logs, even when disabled, it banned players.

**Comment by EinS4ckZwiebeln** [comment]
Hmm, strange. Everything seems to work fine for me... I don't know why this happens to you. The only thing I can imagine is that some files were not overwritten correctly when you updated to v2.0.6. You should try re-downloading them and replacing them all.

**Comment by YelehaUwU** [comment]
I replaced all except the config.

**Comment by EinS4ckZwiebeln** [comment]
> I replaced all except the config.


You should replace that one as well. There were changes made in v2.0.6.


**If you can attach the app.js file from the /dist/ directory, I may be able to find the problem if I dig through that.**

**Comment by YelehaUwU** [comment]
[app.js.txt](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/14967253/app.js.txt)
I attached it (.txt because github only accepts that). I've changed the config just in case.

**Comment by YelehaUwU** [comment]
Can't reproduce the issue anymore after updating app.js
