### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yusinan666** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#69]
![image](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/163602261/8ddbbc3c-2d99-4886-ae25-308bc729c6a7)

hi, can you help me see what the problem is
Anti-cheat doesn't work

**Comment by EinS4ckZwiebeln** [comment]
Hi, this looks like you have an issue with your Discord webhook URL or something else that prevents posting a request to the webhook URL. If you can attach the correct debug and error logs from `Icarus/logs` I might be able to nail down the problem further :)

**Comment by yusinan666** [comment]
[debug-2024-05-20.log](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15436249/debug-2024-05-20.log)
[debug-2024-05-21.log](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15436251/debug-2024-05-21.log)
[error-2024-05-20.log](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15436252/error-2024-05-20.log)
[error-2024-05-21.log](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15436253/error-2024-05-21.log)

**Comment by yusinan666** [comment]
[logs.zip](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15436281/logs.zip)

**Comment by yusinan666** [comment]
sorry I haven't seen much of GitHub
