### ISSUE TITLE
Player Names

### ISSUE THREAD

**Issue by 01stoolie** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#77]
Hello! I was thinking that there should be a bypass for certain members to have special characters in their names, in my own server we use for example !101 so I want to restrict it to only management members because some members put weird things in their names and it's getting out of control. I think it would be a good idea for my server in general but it would be good if that could be added.

**Comment by EinS4ckZwiebeln** [comment]
Hi, I will look into this, but I'm not sure if classic ace permission checks are possible while deferring. This needs some testing.

**Comment by EinS4ckZwiebeln** [comment]
In this new [pre-release](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/releases/tag/release-pre-2.1.1) you should be able to add bypasses for the connection deferring.

`add_ace group.<group_name> icarus.deferrals_module allow`

**Comment by EinS4ckZwiebeln** [comment]
Merged fix into latest release.
