### ISSUE TITLE
somehow it doesnt ban a player if he stop resource and enabled in config.

### ISSUE THREAD

**Issue by leander-hyphen** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#9]

**Comment by EinS4ckZwiebeln** [comment]
Any details on how the player stops the resource? Cheating or just testing?

**Comment by leander-hyphen** [comment]
eulen stop resource.

**Comment by EinS4ckZwiebeln** [comment]
Released an update that **may** resolve this issue, although I can't guarantee that you won't be able to stop resources on the client.
